#!/usr/bin/env python3
"""Generate references.bib from references.tsv (citekey<TAB>doi:...|arxiv:...).

Entry keys are rewritten to our citekeys. DOI entries come from doi.org
content negotiation (Crossref/DataCite BibTeX); arXiv entries from the
arxiv.org/bibtex endpoint. Failures are reported and must be hand-added
to references-manual.bib, which is concatenated last.
"""
import re
import sys
import time
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "references.bib"


def split_fields(body):
    """Split a BibTeX entry body into fields at brace depth zero."""
    fields, depth, cur = [], 0, []
    for ch in body:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        if ch == "," and depth == 0:
            fields.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
    fields.append("".join(cur))
    return [f.strip() for f in fields if f.strip()]


def fmt(entry):
    """Re-emit an entry in canonical layout: one lowercased field per
    line, values verbatim. Sources differ (Crossref: one line; arXiv:
    multi-line; manual: hand-wrapped) — this makes them uniform."""
    m = re.match(r"@(\w+)\s*\{\s*([^,]*),(.*)\}\s*$", entry.strip(), re.S)
    if not m:
        return entry.strip()
    kind, key, body = m.groups()
    lines = []
    for field in split_fields(body):
        name, _, value = field.partition("=")
        lines.append(f"  {name.strip().lower()} = {value.strip()},")
    return "@" + kind.lower() + "{" + key.strip() + ",\n" + "\n".join(lines) + "\n}"


def fetch(url, accept=None):
    req = urllib.request.Request(url, headers={"User-Agent": "sys0-bibgen"})
    if accept:
        req.add_header("Accept", accept)
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8", "replace")


def main():
    rows = [
        line.split("\t")
        for line in (HERE / "references.tsv").read_text().splitlines()
        if line.strip()
    ]
    entries, failed = [], []
    for key, ident in rows:
        try:
            if ident.startswith("doi:"):
                bib = fetch(
                    f"https://doi.org/{ident[4:]}",
                    accept="application/x-bibtex",
                )
            elif ident.startswith("arxiv:"):
                bib = fetch(f"https://arxiv.org/bibtex/{ident[6:]}")
            else:
                raise ValueError(f"unknown id scheme: {ident}")
        except Exception as e:
            failed.append((key, ident, str(e)))
            continue
        bib = bib.strip()
        if not bib.startswith("@"):
            failed.append((key, ident, f"non-bibtex response: {bib[:60]!r}"))
            continue
        bib = re.sub(r"^(@\w+\{)[^,]*,", rf"\g<1>{key},", bib, count=1)
        # Brace name particles so citation styles keep them
        # ("van Dinter et al.", not "Dinter et al.").
        bib = bib.replace("author={van Dinter,", "author={{van Dinter},")
        # Crossref emits month=July; typst's biblatex parser only knows
        # the standard three-letter abbreviations.
        bib = re.sub(
            r"\bmonth=([A-Za-z]+)", lambda m: f"month={m.group(1)[:3].lower()}", bib
        )
        entries.append(fmt(bib))
        time.sleep(1)
    manual = HERE / "references-manual.bib"
    if manual.exists():
        raw = manual.read_text()
        entries.extend(
            fmt("@" + e) for e in re.split(r"^@", raw, flags=re.M) if e.strip()
        )
    marker = (
        "% Generated by make-references.py — edit references.tsv or\n"
        "% references-manual.bib instead; hand edits here are overwritten.\n\n"
    )
    OUT.write_text(marker + "\n\n".join(entries) + "\n")
    print(f"{len(entries)} entries ({len(failed)} failed)")
    for key, ident, err in failed:
        print(f"FAILED: {key} ({ident}): {err}", file=sys.stderr)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
